# Generated by Django 4.1.3 on 2022-11-23 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_uz', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('first_name_en', models.CharField(max_length=50, null=True)),
                ('first_name_uz', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('last_name_en', models.CharField(max_length=50, null=True)),
                ('last_name_uz', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=100)),
                ('adress_en', models.CharField(max_length=100, null=True)),
                ('adress_uz', models.CharField(max_length=100, null=True)),
                ('comment', models.CharField(max_length=500)),
                ('comment_en', models.CharField(max_length=500, null=True)),
                ('comment_uz', models.CharField(max_length=500, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmfresh.city')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('first_name_en', models.CharField(max_length=50, null=True)),
                ('first_name_uz', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('last_name_en', models.CharField(max_length=50, null=True)),
                ('last_name_uz', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=50)),
                ('designation_en', models.CharField(max_length=50, null=True)),
                ('designation_uz', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=100)),
                ('adress_en', models.CharField(max_length=100, null=True)),
                ('adress_uz', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=None, upload_to='mobile_images')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmfresh.city')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100)),
                ('description_en', models.CharField(max_length=100, null=True)),
                ('description_uz', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('slug', models.CharField(max_length=250)),
                ('slug_en', models.CharField(max_length=250, null=True)),
                ('slug_uz', models.CharField(max_length=250, null=True)),
                ('author_name', models.CharField(max_length=250)),
                ('author_name_en', models.CharField(max_length=250, null=True)),
                ('author_name_uz', models.CharField(max_length=250, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='mobile_images')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100)),
                ('description_en', models.CharField(max_length=100, null=True)),
                ('description_uz', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('title_en', models.CharField(max_length=20, null=True)),
                ('title_uz', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=350)),
                ('description_en', models.CharField(max_length=350, null=True)),
                ('description_uz', models.CharField(max_length=350, null=True)),
                ('price', models.FloatField(default=0)),
                ('product_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='mobile_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmfresh.category')),
                ('category_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmfresh.category')),
                ('category_uz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmfresh.category')),
            ],
            options={
                'ordering': ['-product_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmfresh.customer')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmfresh.farmer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmfresh.product')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmfresh.country'),
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmfresh.city')),
            ],
        ),
    ]
