# Generated by Django 4.1.3 on 2022-11-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmfresh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='comment',
            field=models.CharField(default='well', max_length=500),
        ),
        migrations.AddField(
            model_name='farmer',
            name='designation',
            field=models.CharField(default='ssssss', max_length=50),
        ),
    ]
