# Generated by Django 4.1.3 on 2022-11-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmfresh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
