# Generated by Django 4.1.3 on 2022-11-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmfresh', '0003_mymodel_alter_customer_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=250),
        ),
    ]
