# Generated by Django 4.1.3 on 2022-11-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmfresh', '0004_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field=50, upload_to='mobile_images', width_field=50),
        ),
    ]
