# Generated by Django 4.1.3 on 2022-11-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmfresh', '0005_features'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
    ]
