# Generated by Django 4.1.3 on 2022-11-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmfresh', '0007_alter_mymodeltranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='go', upload_to='mobile_images'),
            preserve_default=False,
        ),
    ]
