# Generated by Django 4.1.3 on 2022-11-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmfresh', '0008_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uz',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
