# Generated by Django 4.1.3 on 2022-11-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmfresh', '0009_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100)),
                ('description_en', models.CharField(max_length=100, null=True)),
                ('description_uz', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
