# Generated by Django 4.1.3 on 2022-11-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmfresh', '0010_customer_image_feature_image_service_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_images'),
        ),
    ]
